name: ItemBank
main: ElementalMinecraftGaming\ItemBank\Main
version: 1.0.0
api: [3.7.2]
load: POSTWORLD
author: ElementalMinecraftGaming
description: Store your items in a bank!

commands:
 storeitem:
  description: Store an item!
  permission: bank.item
  aliases: [storei]
 retrieveitem:
  description: retrieve your items!
  permission: bankt.item
  aliases: [retrievei]
 bankitem:
  description: check amount of stored items!
  permission: bankt.item
  aliases: [banki]
 bankhelp:
  description: BankItem commands!
  permission: bankt.item
  aliases: [bankh]

permissions:
  bank.item:
    default: true
    description: Let's you use /si {ItemID}
  bankt.item:
    default: true
    description: Let's you use /ri {ItemID}
